### ISSUE TITLE
`authn-jwt-gitlab` binary does not exit with a non-zero status on error

### ISSUE THREAD

**Issue by cmellazchy** [cyberark/authn-jwt-gitlab#12]
**Describe the bug**
The authn-jwt-gitlab does not exit with a non-zero exit code when an error occurs. As a result, even when secret fetching fails due to issues like unauthorized access, missing secrets, or SSL certificate errors, the job is still marked as successful. This is not the desired behavior.

**To Reproduce**
1. Configure authn-jwt-gitlab to fetch a secret following the sample defined [here](https://github.com/cyberark/authn-jwt-gitlab?tab=readme-ov-file#example-gitlab-ci-yaml-file).
2. Ensure a failure scenario occurs (e.g., unauthorized access, non-existent secret, or SSL certificate error).
3. Observe that the process completes with a zero exit code, marking the job as successful despite the failure.

**Expected behavior**
The expected behavior is that `authn-jwt-gitlab` should exit with a non-zero exit code when secret fetching fails, ensuring that failures are correctly propagated and handled.

**Comment by Nirupma-Verma** [comment]
When the binary result and export are called together, the error is being suppressed.
Please try using the following sample configuration, where the script result is stored in a variable first, and then exported:

```
variables:
  CONJUR_APPLIANCE_URL: "https://conjur-server/"
  CONJUR_ACCOUNT: "cucumber"
  CONJUR_AUTHN_JWT_SERVICE_ID: "gitlab"
 
alpine:
  tags:
    - conjur-demo
  id_tokens:
    ID_TOKEN_2:
      aud: http://gitlab.example.com:9080/
  variables:
    CONJUR_AUTHN_JWT_TOKEN: $ID_TOKEN_2
  image: cyberark/authn-jwt-gitlab:alpine-1.0.0
  script:
    - USERNAME=$(CONJUR_SECRET_ID="Dev-Team-credential1" /authn-jwt-gitlab)
    - export TEST_USERNAME="$USERNAME"
```
